---
- hosts: regions
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: python2.7
    smtp_api_endpoint: "inbound-smtp.{{ aws_region }}.amazonaws.com"
    smtp_endpoint: "email-smtp.{{ aws_region }}.amazonaws.com"

  tasks:
    - name: Create MX record
      route53:
        command: create
        record: "{{ mx_domain }}"
        zone: "{{ (mx_zone | d(False)) or omit }}"
        hosted_zone_id: "{{ (mx_zone_id | d(False)) or omit }}"
        type: MX
        ttl: "{{ mx_ttl | d(3600) }}"
        value: "10 {{ smtp_endpoint }}"
        overwrite: yes

    - name: Create S3 bucket
      s3_bucket:
        name: "{{ s3_bucket }}"
        policy: "{{ lookup('template', 'ses_to_s3_policy.json.j2') }}"

    - name: Create SES receipt rule set
      ses_rule_set:
        name: "{{ ses_rule_set_name }}"
        activate: yes

    - name: Create catch-all SES receipt rule
      ses_rule:
        name: "{{ ses_rule_set_name }}01"
        ruleset: "{{ ses_rule_set_name }}"
        recipients:
          - "{{ mx_domain }}"
        actions:
          - S3Action:
              BucketName: "{{ s3_bucket }}"
              ObjectKeyPrefix: "{{ s3_key_prefix | d('') }}"

    - name: Create SNS topic
      sns_topic:
        name: "{{ sns_topic_name }}"
        region: "{{ aws_region }}"
      register: event_topic

    - name: Remove AMAZON_SES_SETUP_NOTIFICATION key
      s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ s3_prefix | d('') }}/AMAZON_SES_SETUP_NOTIFICATION"
        mode: delobj

# vim: ft=ansible
